export interface SearchQuery {
  generalQuery: string
  tags: string[]
  title: string
  content: string
  category: string
  isFavorite?: boolean | undefined
}

// Search operators (case-insensitive). The pt-BR operators are the official ones and the ones
// generated by the app; the English operators are still accepted for backward compatibility.
const VALUE_OPERATORS = {
  title: 'title|t[ií]tulo',
  content: 'content|conte[uú]do',
  category: 'category|categoria',
} as const

type ValueOperatorKey = keyof typeof VALUE_OPERATORS

const TAG_OPERATOR = 'tag'
const FAVORITE_OPERATOR = 'is:favorite|favorito:sim'
const NOT_FAVORITE_OPERATOR = 'is:not-favorite|favorito:n[aã]o'

// Operators must start a token (start of the query or after whitespace), so that
// e.g. "subtitle:x" or "xcontent:y" are not treated as operators
const TOKEN_START = '(?<!\\S)'
// Flag operators must also end a token, so that e.g. "is:favorites" or "favorito:simples" don't match
const TOKEN_END = '(?!\\S)'

// Body of a quoted string: any character except quote/backslash, or a backslash escape (\" or \\),
// so that values containing quotes (e.g. the tag aspas"x) survive a format/parse round trip
const QUOTED_BODY = '(?:[^"\\\\]|\\\\.)*'
// A value is either a quoted string (may contain spaces) or a run of non-space characters
const VALUE_PATTERN = `"(${QUOTED_BODY})"|([^\\s]+)`
// A tag list is one or more comma-separated tags, each quoted or unquoted: tag:IA,"Data Science"
const TAG_ITEM_PATTERN = `(?:"${QUOTED_BODY}"|[^\\s,]+)`
const TAG_LIST_PATTERN = `,*${TAG_ITEM_PATTERN}(?:,+${TAG_ITEM_PATTERN})*,*`

const ALL_VALUE_OPERATORS = Object.values(VALUE_OPERATORS).join('|')

// Single regex that scans the query from left to right, so that the value of one operator
// (e.g. titulo:"a tag:b") is never parsed as another operator
const SEARCH_TOKEN_PATTERN =
  `${TOKEN_START}(?:` +
  `${TAG_OPERATOR}:(?<tags>${TAG_LIST_PATTERN})` +
  `|(?<operator>${ALL_VALUE_OPERATORS}):(?:"(?<quoted>${QUOTED_BODY})"|(?<bare>[^\\s]+))` +
  `|(?<favorite>${FAVORITE_OPERATOR})${TOKEN_END}` +
  `|(?<notFavorite>${NOT_FAVORITE_OPERATOR})${TOKEN_END}` +
  `)`

// An operator typed without a value yet (e.g. "tag:", "titulo:" or "favorito:") is left in the
// free text by the parser; it must be ignored by the search instead of matching nothing
const EMPTY_OPERATOR_REGEX = new RegExp(`^(?:${TAG_OPERATOR}|${ALL_VALUE_OPERATORS}|favorito|is):[",]*$`, 'i')

function unescapeQuoted(value: string): string {
  return value.replace(/\\(["\\])/g, '$1')
}

// A bare value starting with a quote comes from a quote that was not closed yet (titulo:"Revi)
function cleanBareValue(value: string): string {
  return value.replace(/^"/, '')
}

/**
 * Normalizes text for comparisons that ignore case and accents: "Análise" -> "analise".
 */
export function normalizeSearchText(text: string): string {
  return text.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase().trim()
}

/**
 * Splits the free text of a query into normalized search terms: words, or "quoted phrases".
 * Operators still without a value (e.g. "tag:") are dropped.
 */
export function getFreeTextTerms(generalQuery: string): string[] {
  const terms: string[] = []
  const termRegex = new RegExp(`"(${QUOTED_BODY})"|(\\S+)`, 'g')
  let match: RegExpExecArray | null
  while ((match = termRegex.exec(generalQuery)) !== null) {
    let term: string
    if (match[1] !== undefined) {
      term = unescapeQuoted(match[1])
    } else {
      const word = match[2] ?? ''
      if (EMPTY_OPERATOR_REGEX.test(word)) continue
      // Stray quotes (e.g. a phrase not closed yet) are not part of the word
      term = word.replace(/^"+|"+$/g, '')
    }
    const normalized = normalizeSearchText(term)
    if (normalized) {
      terms.push(normalized)
    }
  }
  return terms
}

function resolveValueOperator(operator: string): ValueOperatorKey | undefined {
  return (Object.keys(VALUE_OPERATORS) as ValueOperatorKey[]).find(key =>
    new RegExp(`^(?:${VALUE_OPERATORS[key]})$`, 'i').test(operator)
  )
}

/**
 * Returns a new global, case-insensitive regex that matches a whole filter token
 * (operator + value) of the given type, in any accepted language.
 */
export function getFilterRegex(filterType: 'tag' | ValueOperatorKey | 'favorite'): RegExp {
  switch (filterType) {
    case 'tag':
      return new RegExp(`${TOKEN_START}${TAG_OPERATOR}:${TAG_LIST_PATTERN}`, 'gi')
    case 'favorite':
      return new RegExp(`${TOKEN_START}(?:${FAVORITE_OPERATOR}|${NOT_FAVORITE_OPERATOR})${TOKEN_END}`, 'gi')
    default:
      return new RegExp(`${TOKEN_START}(?:${VALUE_OPERATORS[filterType]}):(?:${VALUE_PATTERN})`, 'gi')
  }
}

/**
 * Splits the value of a tag filter (everything after "tag:") into individual tags.
 */
export function parseTagList(tagList: string): string[] {
  const tags: string[] = []
  const itemRegex = new RegExp(`"(${QUOTED_BODY})"|([^\\s,]+)`, 'g')
  let match: RegExpExecArray | null
  while ((match = itemRegex.exec(tagList)) !== null) {
    const tag = (match[1] !== undefined ? unescapeQuoted(match[1]) : cleanBareValue(match[2] ?? '')).trim()
    if (tag) {
      tags.push(tag)
    }
  }
  return tags
}

export function parseSearchQuery(query: string): SearchQuery {
  const result: SearchQuery = {
    generalQuery: '',
    tags: [],
    title: '',
    content: '',
    category: '',
    isFavorite: undefined
  }

  if (!query.trim()) {
    return result
  }

  const tokenRegex = new RegExp(SEARCH_TOKEN_PATTERN, 'gi')
  const remainingParts: string[] = []
  let lastIndex = 0
  let match: RegExpExecArray | null

  // Extract special patterns
  while ((match = tokenRegex.exec(query)) !== null) {
    const groups = match.groups ?? {}

    // Keep the text between operators as general search text
    remainingParts.push(query.slice(lastIndex, match.index))
    lastIndex = match.index + match[0].length

    if (groups.tags !== undefined) {
      // Handle comma-separated tags: tag:IA,Escrita
      result.tags.push(...parseTagList(groups.tags))
    } else if (groups.operator !== undefined) {
      // For quoted strings the value is in "quoted", otherwise in "bare"
      const value = (groups.quoted !== undefined
        ? unescapeQuoted(groups.quoted)
        : cleanBareValue(groups.bare ?? '')
      ).trim()

      switch (resolveValueOperator(groups.operator)) {
        case 'title':
          result.title = value
          break
        case 'content':
          result.content = value
          break
        case 'category':
          result.category = value
          break
      }
    } else if (groups.favorite !== undefined) {
      result.isFavorite = true
    } else if (groups.notFavorite !== undefined) {
      result.isFavorite = false
    }
  }
  remainingParts.push(query.slice(lastIndex))

  // The remaining query is treated as a general search
  result.generalQuery = remainingParts
    .map(part => part.trim())
    .filter(Boolean)
    .join(' ')

  return result
}

function needsQuotes(value: string): boolean {
  return /[\s,"]/.test(value)
}

function formatValue(value: string): string {
  if (needsQuotes(value)) {
    // Escape quotes and backslashes (undone by the parser) and wrap in quotes
    return `"${value.replace(/["\\]/g, '\\$&')}"`
  }
  return value
}

/**
 * Builds a tag filter token, quoting individual tags if needed: tag:IA,"Data Science"
 */
export function formatTagFilter(tags: readonly string[]): string {
  return `tag:${tags.map(formatValue).join(',')}`
}

export function formatSearchQuery(parsedQuery: SearchQuery): string {
  const parts: string[] = []

  if (parsedQuery.generalQuery) {
    parts.push(parsedQuery.generalQuery)
  }

  if (parsedQuery.tags.length > 0) {
    // Format tags, quoting individual tags if needed
    parts.push(formatTagFilter(parsedQuery.tags))
  }

  if (parsedQuery.title) {
    parts.push(`titulo:${formatValue(parsedQuery.title)}`)
  }

  if (parsedQuery.content) {
    parts.push(`conteudo:${formatValue(parsedQuery.content)}`)
  }

  if (parsedQuery.category) {
    parts.push(`categoria:${formatValue(parsedQuery.category)}`)
  }

  if (parsedQuery.isFavorite === true) {
    parts.push('favorito:sim')
  } else if (parsedQuery.isFavorite === false) {
    parts.push('favorito:nao')
  }

  return parts.join(' ')
}

export function getSearchSuggestions(query: string, availableTags: string[], availableCategories: string[]): string[] {
  const suggestions: string[] = []

  // Tag suggestions (completes the last tag of the list: tag:IA,Es -> tag:IA,Escrita)
  const tagMatch = query.match(/(?<!\S)(tag:(?:[^\s]*,)?)([^,\s]*)$/i)
  if (tagMatch) {
    const prefix = query.slice(0, tagMatch.index) + (tagMatch[1] ?? 'tag:')
    const partial = normalizeSearchText(tagMatch[2] || '')
    const matchingTags = availableTags
      .filter(tag => normalizeSearchText(tag).startsWith(partial))
      .slice(0, 5)

    matchingTags.forEach(tag => {
      suggestions.push(`${prefix}${formatValue(tag)}`)
    })
  }

  // Category suggestions
  const categoryMatch = query.match(/(?<!\S)(?:category|categoria):("([^"]*)"?|([^\s]*))$/i)
  if (categoryMatch) {
    const partial = normalizeSearchText(categoryMatch[2] || categoryMatch[3] || '')
    const matchingCategories = availableCategories
      .filter(cat => normalizeSearchText(cat).startsWith(partial))
      .slice(0, 5)

    matchingCategories.forEach(category => {
      suggestions.push(`${query.slice(0, categoryMatch.index)}categoria:${formatValue(category)}`)
    })
  }

  // Add common search patterns if query is simple
  if (!query.includes(':') && query.trim()) {
    const value = formatValue(query.trim())
    suggestions.push(
      `${query.trim()} favorito:sim`,
      `tag:${value}`,
      `titulo:${value}`,
      `conteudo:${value}`
    )
  }

  return suggestions.slice(0, 8) // Limit to 8 suggestions
}
